name: Build-Table-Of-Contents
on: 
  push:
    paths-ignore:
      - README.md

jobs:
  build-toc:
    name: Build Table of Contents
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install Deno
        uses: denolib/setup-deno@v2
      - name: Build Readme
        run: deno run --allow-read --allow-write --unstable build-toc.js
      - name: Git Config
        run: git config user.email "github_bot@bot.com"  user.name "github_bot"
      - name: Git Add
        run: git add -A
      - name: Git Commit
        run: git commit -m "building toc"
      - name: Git Push
        run: git push origin